language: php
php:
  - "5.6"
env:
  - CI_ENV=unit_testing CI_ROOTED=true
install:
- pyrus install pear/PHP_CodeSniffer
- composer require codeclimate/php-test-reporter --dev
- phpenv rehash
script:
 - bash -xe test-everything.sh
